### ISSUE TITLE
Need AppIcon set for CashierFu Print Extension

### ISSUE THREAD

**Issue by acwright** [cashierfu/CashierFu-Icons#1]
The icon for this must be only black and white! No gradients, no colors. Just black and white. Thanks!

**Comment by peterbarnes** [comment]
Just fixed the icons, there isn't a gradient anymore.

**Comment by acwright** [comment]
Sorry, I don't think I'm being clear about this... The icon for the print extension has to be black and white with no gradients. No gray color!. Just black and white. And please make an icon set for me. Thanks!

**Comment by acwright** [comment]
Look at bottom row of icons in this example picture. The icon has to be just black and white. Then iOS turns it into a "template" image which renders it like it appears in the photo.

![Extension example](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/Art/share_action_appex_2x.png)

**Comment by peterbarnes** [comment]
Check out the new monochrome print icon, that should be correct.

**Comment by acwright** [comment]
Excellent thanks!
